inherits_from:
  - .haml-lint_todo.yml

linters:
  ConsecutiveComments:
    enabled: false
  IdNames:
    enabled: false
  InstanceVariables:
    enabled: false
  LineLength:
    enabled: false
  ViewLength:
    enabled: false
