---
linters:
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  IdSelector:
    enabled: false
  ImportPath:
    enabled: false
  ImportantRule:
    enabled: false
  Indentation:
    enabled: false
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PropertySortOrder:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  SpaceAroundOperator:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  StringQuotes:
    enabled: false
  TrailingSemicolon:
    enabled: false
  VendorPrefix:
    enabled: false
