default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  checkout_timeout: <%= ENV['DB_TIMEOUT'] || 5 %>
  host: localhost
  username: postgres

development:
  <<: *default
  database: btn_group_development

test:
  <<: *default
  database: btn_group_test

production:
  <<: *default
  database: btn_group_production
  username: btn_group
  password: <%= ENV['BTN_GROUP_DATABASE_PASSWORD'] %>